### ISSUE TITLE
Errors when Grakn server is not running are unhelpful

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/console#108]
## Description

When a Grakn server was never running, or was shut down while the user was active in the console, the errors given are internal exceptions rather than giving informative help to the user.

## Reproducible Steps

Two cases are given here:

### Case 1

Without starting a Grakn server, open a console and try to list the databases:
```
> database list
io exception
```
You see a very succinct `io exception` with no helpful prompt!

If you try to open a transaction the exception is more informative, but clearly we can tell the user in this case that there is no server running:
```
> transaction test data read
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at grakn.protocol.GraknGrpc$GraknBlockingStub.sessionOpen(GraknGrpc.java:571)
	at grakn.client.rpc.RPCSession.<init>(RPCSession.java:56)
	at grakn.client.GraknClient.session(GraknClient.java:56)
	at grakn.client.GraknClient.session(GraknClient.java:51)
	at grakn.console.GraknConsole.runTransactionRepl(GraknConsole.java:130)
	at grakn.console.GraknConsole.runRepl(GraknConsole.java:118)
	at grakn.console.GraknConsole.run(GraknConsole.java:70)
	at grakn.console.GraknConsole.main(GraknConsole.java:231)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:1729
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Case 2
Start a Grakn server, create a db called `test` and open a transaction to it. When the transaction is open, shut down the server to see the exception below.
```
> database list
diagnosis
> database create test
Database 'test' created
> transaction test data read
test::data::read> Exception in thread "Timer-0" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at grakn.protocol.GraknGrpc$GraknBlockingStub.sessionPulse(GraknGrpc.java:588)
	at grakn.client.rpc.RPCSession$PulseTask.run(RPCSession.java:112)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:1729
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
The above exception is the same exception as in Case 1, however this time the server also reports an exception, presumably because there was an open transaction when it was shut down:
```
Grakn Core version: 2.0.0-alpha
Grakn Core Server has been started (in 2428 ms)
^C
Shutting down Grakn Core Server...
[SRV09] Invalid Server Operation: Grakn Core server has been shutdown.
grakn.core.common.exception.GraknException: [SRV09] Invalid Server Operation: Grakn Core server has been shutdown.
	at grakn.core.common.exception.GraknException.of(GraknException.java:51)
	at grakn.core.server.rpc.GraknRPCService.lambda$close$1(GraknRPCService.java:175)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at grakn.core.server.rpc.GraknRPCService.close(GraknRPCService.java:175)
	at grakn.core.server.GraknServer.close(GraknServer.java:270)
	at java.lang.Thread.run(Thread.java:748)
Grakn Core Server has been shutdown
```

**Comment by vmax** [comment]
As of https://github.com/graknlabs/console/commit/ca6f963e9e89521ac8327998b6ae386387eefa78, this should no longer be the case.

Case 1: prints a helpful message: `[CLI9] Illegal Client State: Unable to connect to Grakn Core Server.` (fixed in graknlabs/client-java#236)
Case 2: no longer happens because unavailable server is treated correctly by session pulse (fixed in graknlabs/client-java#237)
