### ISSUE TITLE
Exception when trying to enter into the console

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/console#94]
Using Biograkn Covid, I try to get into the console using these commands: 
`./grakn console`
`transaction biograkn_covid_16 data read `
But then I get this warning: 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/tasabat/Documents/GraknDists/grakn-core-all-mac-2.0.0-alpha/console/services/lib/com-google-protobuf-protobuf-java-3-5-1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Despite that warning, I manage to get in the console. However when I run: 
```biograkn_covid_16::data::read> match $g isa protein; ```
I get this error: 
```
[CLI1] Illegal Client State: The transaction has been closed and no further operation is allowed.
```
Then I open a new tab and I do again: 
`./grakn console`
`transaction biograkn_covid_16 data read `
I then get this exception: 
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at grakn.protocol.GraknGrpc$GraknBlockingStub.sessionOpen(GraknGrpc.java:571)
	at grakn.client.rpc.RPCSession.<init>(RPCSession.java:56)
	at grakn.client.GraknClient.session(GraknClient.java:56)
	at grakn.client.GraknClient.session(GraknClient.java:51)
	at grakn.console.GraknConsole.runTransactionRepl(GraknConsole.java:130)
	at grakn.console.GraknConsole.runRepl(GraknConsole.java:118)
	at grakn.console.GraknConsole.run(GraknConsole.java:70)
	at grakn.console.GraknConsole.main(GraknConsole.java:231)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:1729
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Afterwards I am back in the terminal so not in the console anymore.

**Comment by lriuui0x0** [comment]
oh....this re-appears...

**Comment by tomassabat** [comment]
I haven't seen this bug since I reported this on Saturday @lolski

**Comment by lolski** [comment]
@lriuui0x0 said it reappeared, therefore let's keep it open since the issue is valid.

**Comment by lriuui0x0** [comment]
@lolski No I meant the the server crash reappears - I didn't see this issue either.

**Comment by haikalpribadi** [comment]
Are we able to reproduce this bug, @lriuui0x0 @tomassabat ?
