### ISSUE TITLE
"Failed to load history" warning when entering in console

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/console#95]
1. Start Grakn 2.0 
2. Enter the console using `./grakn server`
3. Then the following warning appears: 

```
Welcome to Grakn Console. You are now in Grakn Wonderland!
Copyright (C) 2020 Grakn Labs

Jan 09, 2021 9:04:30 PM org.jline.utils.Log logr
WARNING: Failed to load history
java.lang.IllegalArgumentException: Bad history file syntax! The history file `/Users/tasabat/.grakn-console-history` may be an older history: please remove it or use a different history file.
	at org.jline.reader.impl.history.DefaultHistory.addHistoryLine(DefaultHistory.java:179)
	at org.jline.reader.impl.history.DefaultHistory.addHistoryLine(DefaultHistory.java:169)
	at org.jline.reader.impl.history.DefaultHistory.lambda$load$0(DefaultHistory.java:86)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.jline.reader.impl.history.DefaultHistory.load(DefaultHistory.java:86)
	at org.jline.reader.impl.history.DefaultHistory.attach(DefaultHistory.java:69)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:594)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:459)
	at grakn.console.Utils.getTokens(Utils.java:49)
	at grakn.console.ReplCommand.getCommand(ReplCommand.java:120)
	at grakn.console.GraknConsole.runRepl(GraknConsole.java:84)
	at grakn.console.GraknConsole.run(GraknConsole.java:70)
	at grakn.console.GraknConsole.main(GraknConsole.java:231)
```

**Comment by lriuui0x0** [comment]
This is caused by we're using 2.0 and 1.8 at the same machine and they write to the same history file with different syntax. We may just need to rename the history file in 2.0.
